sudo: required
dist: trusty
addons:
  apt:
    packages:
      - mtools
      - python3
      - python3-pip
      - expect-dev

language: bash

before_script:
  - ulimit -c unlimited -S
  
script:
  - chmod +x ./build.sh ./upload.sh
  - sudo ./build.sh
  - sudo ./upload.sh
